student_courses = [['Adrian Meraneos', 'meraneosa22', ['free_dot', 'free_dot', 'Physics', 'free_dot', 'AP Chemistry', 'Honors Precalculus', 'free_dot']],
                   ['Aidan Mahoney', 'mahoneya21', ['free_dot', 'Drawing 1', 'US History', 'American Literature', 'Spanish 3', 'Biology', 'Precalculus']],
                   ['Aidan Ryan', 'ryana20', ['Mathematics of Financial Matters', 'free_dot', 'Drawing 1', 'Banned Books and Films', 'free_dot', 'free_dot', 'Baseball and American Culture']],
                   ['Alex Collins', 'collinsa23'], ["Alex O'Neil", 'oneila21', ['free_dot', 'US History', 'American Literature', 'Ceramics: Functional Form', 'Spanish 3', 'Biology', 'Precalculus']],
                   ['Alexa Daigle', 'daiglea21', ['AP Calculus', 'AP US History', 'free_dot', 'free_dot', 'AP Chemistry', 'AP Language and Composition', 'Honors Spanish 4: Literature of Spain']],
                   ['Alexander Baribeau', 'baribeaua21', ['Biology', 'Honors Precalculus', 'AP US History', 'Ceramics: Functional Form', 'free_dot', 'AP Language and Composition', 'French 3']],
                   ['Alexander Hamadeh', 'hamadeha22', ['Geometry', 'Chemistry', 'French 2', 'The West and the World', 'European Literature', 'free_dot', 'free_dot']],
                   ['Alexia Zhou', 'zhouh20', ['Honors Senior Math', 'free_dot', 'free_dot', 'AP Literature and Composition', 'French 4', 'AP Physics: Electricity and Magnetism', 'free_dot']],
                   ['Allison Waugh', 'waugha22', ['free_dot', 'Metal Design 1', 'Honors Algebra 2', 'Spanish 2', 'European Literature', 'Honors Chemistry', 'The West and the World']],
                   ['Amelia McMillan', 'mcmillana20', ['free_dot', 'free_dot', 'free_dot', 'AP United States Government and Politics', 'French 4', 'AP Statistics', 'AP Literature and Composition']],
                   ['Annabelle Darby', 'darbya20', ['free_dot', 'free_dot', 'free_dot', 'AP United States Government and Politics', 'French 5', 'AP Statistics', 'AP Literature and Composition']],
                   ['Annabelle Forsley', 'forsleya21', ['Biology', 'Honors Precalculus', 'AP US History', 'free_dot', 'free_dot', 'AP Language and Composition', 'French 3']],
                   ['Auburn', 'putzburtona21', ['free_dot', 'Honors Precalculus', 'AP US History', 'Academic Skills Program', 'French 4', 'AP Language and Composition', 'Research Methods in Science']],
                   ['Aurelio Flores', 'floresa24', ['free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot']],
                   ['Austin Colby', 'colbyk20', ['Honors Senior Math', 'free_dot', 'free_dot', 'Banned Books and Films', 'AP Biology', 'Social Entrepreneurship', 'Baseball and American Culture']],
                   ['Bella Wang', 'wangj21', ['Honors Senior Math', 'AP US History', 'free_dot', 'American Literature', 'Computer Science', 'AP Physics: Electricity and Magnetism', 'French 3']],
                   ['Blake Norris', 'norrisb25', ['free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot']],
                   ['Bochao Xu', 'xub22'],
                   ['Bridget Sapak', 'sapakb26', ['free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot']],
                   ['Brodie Goclowski', 'goclowskib20', ['free_dot', 'free_dot', 'Literature as Social Commentary', 'AP United States Government and Politics', 'Environmental Science', 'AP Statistics', 'free_dot']],
                   ['Burke MacLeay', 'macleayb22', ['free_dot', 'free_dot', 'Physics', 'The West and the World', 'Spanish 2', 'Honors Chemistry', 'European Literature']],
                   ['Byron An', 'anb23', ['free_dot', 'Conceptual Physics', 'World Literature', 'English Studies: Tutorial', 'Human Geography', 'Honors Algebra 2', 'Band']],
                   ['Caleb Grammas', 'grammasc21', ['free_dot', 'Chemistry', 'French 2', 'European Literature', 'Algebra 2', 'free_dot', 'The West and the World']],
                   ['Caleb Mitchell', 'mitchellc22', ['free_dot', 'European Literature', 'Chemistry', 'Spanish 2', 'The West and the World', 'Algebra 2', 'free_dot']],
                   ['Cameron Simard', 'simardc20', ['Honors Senior Math', 'free_dot', 'free_dot', 'AP United States Government and Politics', 'French 5', 'free_dot', 'AP Literature and Composition']],
                   ['Caroline Newell', 'newellc20', ['free_dot', 'Piano and Keyboard Studies', 'free_dot', 'AP United States Government and Politics', 'French 4', 'AP Statistics', 'AP Literature and Composition']],
                   ['Caroline Siekman', 'siekmanc22', ['free_dot', 'Honors Precalculus', 'European Literature', 'Spanish 2', 'The West and the World', 'Honors Chemistry', 'free_dot']],
                   ['Cassie Pyle', 'pylec21', ['Precalculus', 'Biology', 'AP US History', 'Banned Books and Films', 'free_dot', 'AP Language and Composition', 'French 3']],
                   ['Cate Maccini', 'maccinic22', ['Academic Skills Program', 'Geometry', 'Chemistry', 'Digital Photography 1', 'European Literature', 'free_dot', 'The West and the World']],
                   ['Catherine Caggiano', 'caggianoc23', ['Geometry', 'free_dot', 'French 2', 'Human Geography', 'Conceptual Physics', 'World Literature', 'Art Foundations']],
                   ['Cecille Anderson', 'andersonc20', ['Precalculus', 'free_dot', 'Literature as Social Commentary', 'AP United States Government and Politics', 'Literature of Adventure and Exploration', 'Anatomy & Physiology', 'free_dot']],
                   ['Celeste Fisher', 'fisherc21', ['Biology', 'AP US History', 'free_dot', 'free_dot', 'Spanish 3', 'Algebra 2', 'AP Language and Composition']],
                   ['Chaia Alford', 'alfordc20', ['AP Calculus', 'Metal Design 2', 'free_dot', 'AP United States Government and Politics', 'AP Biology', 'free_dot', 'AP Literature and Composition']],
                   ['Charlotte Long', 'longc26', ['free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot']],
                   ['Chase Fu', 'fub20', ['Mathematics of Financial Matters', 'Biology', 'free_dot', 'Banned Books and Films', 'English Studies: Tutorial', 'AP Statistics', 'free_dot']],
                   ['Chelsea Duclos', 'duclosc23', ['free_dot', 'Geometry', 'Conceptual Physics', 'Human Geography', 'Spanish 2', 'World Literature', 'Art Foundations']],
                   ['Daduo Wang', 'wangd23', ['Spanish 1 LAB', 'Conceptual Physics', 'World Literature', 'Spanish 1', 'English Studies: Academic Reading & Writing 2', 'Human Geography', 'Geometry']],
                   ['Dali Gao', 'gaod22', ['French 1', 'Honors Precalculus', 'free_dot', 'French 1 LAB', 'European Literature', 'Honors Chemistry', 'The West and the World']],
                   ['Danning Dong', 'dongd23', ['free_dot', 'World Literature', 'Honors Algebra 2', 'Spanish 1', 'Conceptual Physics', 'Human Geography', 'free_dot']],
                   ['Dante Maravell', 'maravelld23', ['French 1', 'World Literature', 'Conceptual Physics', 'French 1 LAB', 'Human Geography', 'Introduction to Music', 'Geometry']],
                   ['Drew Curtis', 'curtisd20', ['Spanish 4', 'AP Calculus', 'free_dot', 'AP United States Government and Politics', 'Literature of Adventure and Exploration', 'AP Statistics', 'free_dot']],
                   ['Dylan Greenberg', 'greenbergd21', ['Biology', 'AP Calculus', 'Underwater Robotics', 'free_dot', 'Spanish 3', 'AP Physics: Electricity and Magnetism', 'American Literature']],
                   ['Dylan Rivard', 'rivardd19', ['free_dot', '3D Design with CAD', 'free_dot', 'Introduction to Graphic Design', 'Literature of Adventure and Exploration', 'Social Entrepreneurship', 'Baseball and American Culture']],
                   ['Eamon Wakefield', 'wakefielde20', ['free_dot', 'Drawing 2', 'Presenting Great Decisions', 'AP United States Government and Politics', 'Environmental Science', 'free_dot', 'AP Literature and Composition']],
                   ['Elena Weimar', 'weimare23'],
                   ['Eli Shifrin', 'shifrine23', ['Spanish 1', 'Conceptual Physics', 'World Literature', 'Digital Photography 1', 'Human Geography', 'Introduction to Music', 'Geometry']],
                   ['Elijah Grammas', 'grammase20', ['Music Technology', 'free_dot', 'free_dot', 'American Literature', 'US History', 'Spanish 3', 'Precalculus']],
                   ['Elizabeth Skillings', 'skillingse21', ['Biology', 'free_dot', 'AP US History', 'Banned Books and Films', 'free_dot', 'Honors Precalculus', 'AP Language and Composition']],
                   ['Ella Blair', 'blaire20', ['Academic Skills Program', 'Physics', 'Literature as Social Commentary', 'AP United States Government and Politics', 'Calculus', 'Anatomy & Physiology', 'free_dot']],
                   ['Ella Raymond', 'raymonde21', ['Spanish 4', 'AP US History', 'Chemistry', 'free_dot', 'Calculus', 'Anatomy & Physiology', 'AP Language and Composition']],
                   ['Emalee Coffin', 'coffine21', ['free_dot', 'Biology', 'Presenting Great Decisions', 'Banned Books and Films', 'US History', 'AP Language and Composition', 'French 3']],
                   ['Emma Sullivan', 'sullivane22', ['Honors Chemistry', 'European Literature', 'Honors Algebra 2', 'The West and the World', 'free_dot', 'Spanish 3', 'Art Foundations']],
                   ['Eric Lee', 'leee21', ['Biology', 'free_dot', 'AP US History', 'Banned Books and Films', 'free_dot', 'AP Statistics', 'AP Language and Composition']],
                   ['Esther Lang', 'langy20', ['Mathematics of Financial Matters', 'free_dot', 'Presenting Great Decisions', 'Banned Books and Films', 'AP Biology', 'AP Statistics', 'Research Methods in Science']],
                   ['Ethan Bouchard', 'boucharde23', ['Conceptual Physics', 'Drawing 1', 'Algebra 1', 'Human Geography', 'Spanish 2', 'World Literature', 'free_dot']],
                   ['Evanthia Stasinos', 'stasinose23', ['Academic Skills Program', 'Conceptual Physics', 'World Literature', 'Human Geography', 'Spanish 2', 'Social Entrepreneurship', 'Geometry']],
                   ['Fancheng Li', 'lif22', ['Honors Chemistry', 'free_dot', 'European Literature', 'Chorus', 'The West and the World', 'Algebra 2', 'free_dot']],
                   ['Finnian McLaughlin', 'mclaughlinf20', ['Mathematics of Financial Matters', 'free_dot', 'free_dot', 'Banned Books and Films', 'Astronomy', 'free_dot', 'Baseball and American Culture']],
                   ['Gaku Wada', 'wadag21', ['Precalculus', 'Physics', 'European Literature', 'English Studies: Tutorial', 'The West and the World', 'free_dot', 'Academic Skills Program']],
                   ['Gavin Liu', 'liuz23', ['free_dot', 'English Studies: Academic Reading & Writing 1', 'Conceptual Physics', 'World Literature', 'Algebra 2', 'free_dot', 'Human Geography']],
                   ['Gregory Vlcek', 'vlcekg22', ['Arduinos and Electronics', 'Chemistry', 'The West and the World', 'European Literature', 'Spanish 2', 'Algebra 2', 'free_dot']],
                   ['Haley Hessinger', 'hessingerh22', ['free_dot', 'European Literature', 'The West and the World', 'Digital Photography 1', 'Spanish 2', 'Honors Algebra 2', 'Chemistry']],
                   ['Hannah Hall', 'hallh22', ['French 1', 'free_dot', 'Chemistry', 'French 1 LAB', 'European Literature', 'free_dot', 'Geometry']],
                   ['Hannah McMillan', 'mcmillanh22', ['free_dot', 'Metal Design 1', 'European Literature', 'Spanish 2', 'Algebra 2', 'Honors Chemistry', 'The West and the World']],
                   ['Hannah Pierce', 'pierceh22', ['Geometry', 'Chemistry', 'French 2', 'European Literature', 'The West and the World', 'Algebra 2', 'free_dot']],
                   ['Harrison Connors', 'connorsh22', ['Geometry', 'Chemistry', 'The West and the World', 'free_dot', 'Spanish 2', 'free_dot', 'European Literature']],
                   ['Harrison Keen', 'harrisonk24', ['free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot']],
                   ['Henry Blair', 'blairh22', ['Geometry', 'Chemistry', 'European Literature', 'The West and the World', 'Spanish 2', 'free_dot', 'Academic Skills Program']],
                   ['Henry Melnik', 'melnikh21', ['Precalculus', 'Biology', 'US History', 'free_dot', 'Spanish 3', 'free_dot', 'American Literature']],
                   ['Hunter Bernard', 'bernardh20', ['Precalculus', 'Metal Design 1', 'free_dot', 'AP United States Government and Politics', 'free_dot', 'Anatomy & Physiology', 'AP Literature and Composition']],
                   ['Hunter Curtis', 'curtish21', ['free_dot', 'AP US History', 'American Literature', 'free_dot', 'Spanish 3', 'Biology', 'Precalculus']],
                   ['Ian Tyson', 'tysoni21', ['Arduinos and Electronics', 'US History', 'Academic Skills Program', 'free_dot', 'Algebra 2', 'Biology', 'American Literature']],
                   ['Ingrid Janicki', 'janickii24', ['free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot']],
                   ['Isabel Chase', 'chasei20', ['Mathematics of Financial Matters', 'Piano and Keyboard Studies', 'free_dot', 'AP United States Government and Politics', 'French 5', 'free_dot', 'AP Literature and Composition']],
                   ['Isabella Cortes Greene', 'cortesi22', ['free_dot', 'free_dot', 'Chemistry', 'The West and the World', 'European Literature', 'Algebra 2', 'free_dot']],
                   ['Isabelle Long', 'longi23', ['free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot']],
                   ['Isaiah Connolly', 'connollyi23', ['Spanish 1', 'Conceptual Physics', 'Algebra 1', 'World Literature', 'Human Geography', 'free_dot', 'Band']],
                   ['Isaiah Osborn', 'osborni20', ['Precalculus', 'free_dot', 'free_dot', 'AP Literature and Composition', 'Independent Study: Environmental Science', 'Spanish 3', 'free_dot']],
                   ['J T', 'tseg22', ['Honors Chemistry', 'European Literature', 'Mandarin 2', 'free_dot', 'Computer Science', 'Honors Algebra 2', 'The West and the World']],
                   ['Jackie Li', 'lij21', ['Biology', 'AP Calculus', 'American Literature', 'free_dot', 'US History', 'AP Statistics', 'Research Methods in Science']],
                   ['Jackie Yang', 'yangy23', ['free_dot', 'World Literature', 'Physics', 'Human Geography', 'English Studies: Tutorial', 'Honors Precalculus', 'Band']],
                   ['Jake Plummer', 'plummerj20', ['Precalculus', 'Piano and Keyboard Studies', 'Literature as Social Commentary', 'AP United States Government and Politics', 'Environmental Science', 'free_dot', 'Spanish 5: Literature of Spain']],
                   ['Jake Tamalunas', 'tamalunasj21', ['Precalculus', 'Biology', 'free_dot', 'Ceramics: Functional Form', 'US History', 'Spanish 3', 'American Literature']],
                   ['James Wu', 'wuj22', ['Arduinos and Electronics', 'AP US History', 'American Literature', 'free_dot', 'free_dot', 'Biology', 'Precalculus']],
                   ['Jayda Tamalunas', 'tamalunasj20', ['Mathematics of Financial Matters', 'free_dot', 'Drawing 1', 'Banned Books and Films', 'Environmental Science', 'free_dot', 'Baseball and American Culture']],
                   ['Jeerakit Kanokthipphayakun', 'kanokthipphayakunj20', ['Honors Senior Math', '3D Design with CAD', 'US History', 'free_dot', 'English Studies: Academic Reading & Writing 2', 'AP Physics: Electricity and Magnetism', 'American Literature']],
                   ['Jelena Perovic', 'perovicj22', ['free_dot', 'English Studies: Academic Reading & Writing 1', 'European Literature', 'free_dot', 'The West and the World', 'Algebra 2', 'Chemistry']],
                   ['Jenna Burnett', 'burnettj21', ['Precalculus', 'AP US History', 'Chemistry', 'free_dot', 'free_dot', 'AP Language and Composition', 'Honors Spanish 4: Literature of Spain']],
                   ['Jiahui Yu', 'yuj21', ['free_dot', 'US History', 'American Literature', 'English Studies: Tutorial', 'Environmental Science', 'Honors Chemistry', 'Precalculus']],
                   ['Jianing Li', 'lij20', ['free_dot', 'Physics', 'Presenting Great Decisions', 'American Literature', 'Calculus', 'free_dot', 'Research Methods in Science']],
                   ['Jie Zhou', 'zhouj23', ['Conceptual Physics', 'English Studies: Academic Reading & Writing 1', 'free_dot', 'World Literature', 'Human Geography', 'Honors Precalculus', 'free_dot']],
                   ['Jingxuan Chen', 'chenj22', ['Introduction to Computer Science', 'European Literature', 'Honors Algebra 2', 'The West and the World', 'English Studies: Academic Reading & Writing 2', 'Honors Chemistry', 'free_dot']],
                   ['Jingyuan Zeng', 'zengj20', ['AP Calculus', 'free_dot', 'Physics', 'Introduction to Graphic Design', 'Literature of Adventure and Exploration', 'free_dot', 'Baseball and American Culture']],
                   ['Joseph Herlihy', 'herlihyj24', ['free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot']],
                   ['Joseph Senner', 'sennerj22', ['Geometry', 'European Literature', 'Chemistry', 'Spanish 2', 'The West and the World', 'free_dot', 'free_dot']],
                   ['Joseph Tomaselli', 'tomasellij23', ['free_dot', 'free_dot', 'Conceptual Physics', 'Human Geography', 'Academic Skills Program', 'World Literature', 'Geometry']],
                   ['Junrui Cheng', 'chengj23', ['free_dot', 'English Studies: Academic Reading & Writing 1', 'Honors Algebra 2', 'World Literature', 'Conceptual Physics', 'free_dot', 'Human Geography']],
                   ['Justin Colby', 'colbyj22', ['Honors Chemistry', 'Honors Precalculus', 'European Literature', 'The West and the World', 'free_dot', 'free_dot', 'French 3']],
                   ['Kai Kostmayer', 'kostmayerk20', ['Precalculus', 'free_dot', 'free_dot', 'Banned Books and Films', 'free_dot', 'Anatomy & Physiology', 'free_dot']],
                   ['Kaitlyn Saidy', 'saidyk21', ['Artist Blacksmithing: Functional Ironwork', 'Honors Precalculus', 'AP US History', 'Chorus', 'French 4', 'AP Language and Composition', 'Research Methods in Science']],
                   ['Kaiyi Xiao', 'xiaok22', ['English Studies: Academic Reading & Writing 2', 'Honors Precalculus', 'European Literature', 'free_dot', 'The West and the World', 'Honors Chemistry', 'free_dot']],
                   ['Kalena Medeiros', 'medeirosk21', ['Precalculus', 'US History', 'free_dot', 'free_dot', 'Spanish 3', 'Biology', 'AP Language and Composition']],
                   ['Kamran Duenwald', 'duenwaldk24', ['free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot']],
                   ['Kayla Hosmer', 'hosmerk22', ['free_dot', 'Chemistry', 'French 2', 'European Literature', 'Algebra 2', 'free_dot', 'The West and the World']],
                   ['Ke Dong', 'dongk22', ['AP Calculus', 'free_dot', 'Physics', 'free_dot', 'US History', 'AP Statistics', 'American Literature']],
                   ['Keara Medeiros', 'medeirosk23', ['Geometry', 'free_dot', 'Conceptual Physics', 'Human Geography', 'Spanish 2', 'World Literature', 'Art Foundations']],
                   ['Keiko Yuasa', 'yuasak22', ['free_dot', 'Chemistry', 'French 2', 'The West and the World', 'European Literature', 'Algebra 2', 'Geometry']],
                   ['Kevin Kim', 'kimj21', ['Honors Senior Math', 'US History', 'Mandarin 2', 'American Literature', 'free_dot', 'AP Physics: Electricity and Magnetism', 'Research Methods in Science']],
                   ['Kevin Mutindwa', 'mutindwak23', ['Spanish 1', 'Geometry', 'World Literature', 'free_dot', 'Conceptual Physics', 'Social Entrepreneurship', 'Human Geography']],
                   ['Kyle Rivard', 'rivardk21', ['Precalculus', 'Biology', 'US History', 'American Literature', 'free_dot', 'free_dot', 'French 3']],
                   ['Kyra Shankar', 'shankark23', ['Conceptual Physics', 'Geometry', 'World Literature', 'Human Geography', 'Spanish 2', 'free_dot', 'Band']],
                   ['Laura Wilson', 'wilsonl20', ['free_dot', 'AP Calculus', 'free_dot', 'AP United States Government and Politics', 'French 5', 'free_dot', 'AP Literature and Composition']],
                   ['Leah Ohms', 'ohmsl21', ['Biology', 'US History', 'American Literature', 'Ceramics: Functional Form', 'Algebra 2', 'Academic Skills Program', 'Spanish 5: Literature of Spain']],
                   ['Lexi Ordway', 'ordwaya21', ['free_dot', 'free_dot', 'AP US History', 'free_dot', 'AP Chemistry', 'AP Language and Composition', 'Honors Spanish 4: Literature of Spain']],
                   ['Liam Hourihan', 'hourihanl21', ['Spanish 4', 'AP Calculus', 'free_dot', 'Banned Books and Films', 'Astronomy', 'Anatomy & Physiology', 'Baseball and American Culture']],
                   ['Lillian Drew', 'drewl20', ['free_dot', 'AP Calculus', 'free_dot', 'AP Literature and Composition', 'French 4', 'Anatomy & Physiology', 'free_dot']],
                   ['Lillie King', 'kingl22', ['Spanish 1 LAB', 'free_dot', 'Algebra 1', 'Spanish 1', 'Conceptual Physics', 'World Literature', 'Human Geography']],
                   ['Lily Hall', 'halll23', ['free_dot', 'Geometry', 'World Literature', 'Spanish 2', 'Conceptual Physics', 'Human Geography', 'Band']],
                   ['Lily Ryan', 'ryanl22', ['free_dot', 'Drawing 1', 'French 2', 'European Literature', 'Algebra 2', 'free_dot', 'The West and the World']],
                   ['Lily Winch', 'winchl23', ['Conceptual Physics', 'free_dot', 'Mandarin 1', 'free_dot', 'Human Geography', 'World Literature', 'Geometry']],
                   ['Lindsey Kean', 'keanl23', ['Spanish 1 LAB', 'World Literature', 'Conceptual Physics', 'Spanish 1', 'Human Geography', 'Introduction to Music', 'Geometry']],
                   ['Lisa Herrmann', 'herrmannl23', ['free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot']],
                   ['LiuLu Yue', 'yuel20', ['Honors Senior Math', 'Biology', 'free_dot', 'AP United States Government and Politics', 'Astronomy', 'AP Physics: Electricity and Magnetism', 'AP Literature and Composition']],
                   ['Liwen Xiao', 'xiaol22', ['Honors Chemistry', '3D Design with CAD', 'European Literature', 'The West and the World', 'English Studies: Tutorial', 'Honors Precalculus', 'free_dot']],
                   ['Lucy Towle', 'towlel23', ['French 1', 'World Literature', 'Conceptual Physics', 'French 1 LAB', 'Human Geography', 'Social Entrepreneurship', 'Geometry']],
                   ['Luke Goff', 'goffl24', ['free_dot', 'Academic Skills Program', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot']],
                   ['Lydia', 'bennettl21', ['free_dot', 'Honors Precalculus', 'AP US History', 'Chorus', 'AP Chemistry', 'AP Language and Composition', 'French 3']],
                   ['Lyla Thompson', 'thompsonl20', ['Mathematics of Financial Matters', 'AP Calculus', 'History of Indigenous Peoples of America', 'Banned Books and Films', 'AP Biology', 'free_dot', 'free_dot']],
                   ['Lyman Ordway', 'ordwayl24', ['free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot']],
                   ['Mac Connor', 'connorm24', ['free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot']],
                   ['Maddy Lieblein', 'liebleinm20', ['Honors Senior Math', 'free_dot', 'Presenting Great Decisions', 'AP Literature and Composition', 'AP Biology', 'Anatomy & Physiology', 'Honors Spanish 4: Literature of Spain']],
                   ['Madeline Lindquist', 'lindquistm22', ['free_dot', 'European Literature', 'Chemistry', 'Spanish 2', 'The West and the World', 'free_dot', 'Geometry']],
                   ['Madisyn Bean', 'beanm22', ['Geometry', 'Chemistry', 'The West and the World', 'European Literature', 'Spanish 2', 'free_dot', 'free_dot']],
                   ['Maia Garfield', 'garfieldm20', ['AP Calculus', 'free_dot', 'free_dot', 'Introduction to Graphic Design', 'Literature of Adventure and Exploration', 'Anatomy & Physiology', 'Spanish 5: Literature of Spain']],
                   ['Margaux Van Inwegen', 'vaninwegenm21', ['Academic Skills Program', 'Chemistry', 'Presenting Great Decisions', 'free_dot', 'Literature of Adventure and Exploration', 'Algebra 2', 'French 3']],
                   ['Mason Berlinghoff', 'berlinghoffm21', ['Precalculus', 'Biology', 'Mandarin 2', 'free_dot', 'US History', 'free_dot', 'American Literature']],
                   ['Maxim Epstein', 'epsteinm22', ['Mathematics of Financial Matters', 'AP US History', 'Mandarin 3', 'American Literature', 'free_dot', 'Honors Precalculus', 'Chemistry']],
                   ['Maxwell Hessinger', 'hessingerm20', ['free_dot', 'free_dot', 'free_dot', 'AP United States Government and Politics', 'AP Biology', 'AP Physics: Electricity and Magnetism', 'AP Literature and Composition']],
                   ['Maxx Parys', 'parysm20', ['Honors Senior Math', 'free_dot', 'free_dot', 'Banned Books and Films', 'AP Biology', 'Anatomy & Physiology', 'Baseball and American Culture']],
                   ['Megan Riley', 'rileym24', ['free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot']],
                   ['Meitong Chen', 'chenm23', ['English Studies: Academic Reading & Writing 2', 'Conceptual Physics', 'Honors Algebra 2', 'World Literature', 'free_dot', 'Human Geography', 'Band']],
                   ['Mia Wang', 'wangc21', ['Honors Senior Math', 'Biology', 'US History', 'Digital Photography 1', 'AP Chemistry', 'AP Language and Composition', 'Research Methods in Science']],
                   ['Mikiya Hoshiai', 'hoshiaim23', ['Conceptual Physics', 'English Studies: Academic Reading & Writing 1', 'Honors Algebra 2', 'World Literature', 'Human Geography', 'free_dot', 'free_dot']],
                   ['Min Kim', 'kimm20', ['AP Calculus', 'free_dot', 'Mandarin 3', 'AP United States Government and Politics', 'Computer Science', 'free_dot', 'AP Literature and Composition']],
                   ['Molly Grocki', 'grockim23', ['Conceptual Physics', 'Geometry', 'World Literature', 'Human Geography', 'Spanish 2', 'Introduction to Music', 'free_dot']],
                   ['Myles Barrett', 'barrettm20', ['Mathematics of Financial Matters', 'free_dot', 'History of Indigenous Peoples of America', 'Digital Photography 1', 'Literature of Adventure and Exploration', 'Anatomy & Physiology', 'free_dot']],
                   ['Nathan Livingood', 'livingoodn22', ['Geometry', 'US History', 'Chemistry', 'free_dot', 'European Literature', 'Spanish 3', 'Academic Skills Program']],
                   ['Nathan Pare', 'paren23', ['Spanish 1 LAB', 'Conceptual Physics', 'Algebra 1', 'Spanish 1', 'Human Geography', 'World Literature', 'free_dot']],
                   ['Natsuki Tominaga', 'tominagan23', ['Geometry', 'English Studies: Academic Reading & Writing 1', 'Conceptual Physics', 'Human Geography', 'free_dot', 'World Literature', 'free_dot']],
                   ['Nick Szuba', 'szuban20', ['AP Calculus', 'Physics', 'free_dot', 'Banned Books and Films', 'free_dot', 'AP Statistics', 'Baseball and American Culture']],
                   ['Nina Goldman', 'goldmann23', ['free_dot', 'World Literature', 'Algebra 1', 'free_dot', 'Conceptual Physics', 'Human Geography', 'French 3']],
                   ['Noah Goldman', 'goldmann22', ['French 1', 'Chemistry', 'European Literature', 'French 1 LAB', 'Algebra 2', 'free_dot', 'The West and the World']],
                   ['Nolan Raymond', 'raymondn23', ['Conceptual Physics', 'Drawing 1', 'World Literature', 'Spanish 2', 'Algebra 2', 'Human Geography', 'free_dot']],
                   ['Oliver Barrett', 'barretto23', ['Spanish 1 LAB', 'Geometry', 'free_dot', 'Spanish 1', 'Conceptual Physics', 'World Literature', 'Human Geography']],
                   ['Olivia Cordeiro', 'cordeiroo21', ['Biology', 'Honors Precalculus', 'AP US History', 'free_dot', 'free_dot', 'AP Language and Composition', 'Honors Spanish 4: Literature of Spain']],
                   ['Olivia Hagan', 'hagano24', ['free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot']],
                   ['Olivia Knight', 'knighto21', ['Precalculus', 'free_dot', 'free_dot', 'free_dot', 'Environmental Science', 'Spanish 3', 'AP Language and Composition']],
                   ['Paige Mull', 'mullp22', ['Honors Chemistry', 'European Literature', 'French 2', 'free_dot', 'The West and the World', 'Algebra 2', 'free_dot']],
                   ['Payton Berry', 'berryp23', ['Spanish 1', 'World Literature', 'Algebra 1', 'Spanish 1 LAB', 'Conceptual Physics', 'Human Geography', 'Art Foundations']],
                   ['Peyton Meader', 'meaderp22', ['Honors Chemistry', '3D Design with CAD', 'European Literature', 'Spanish 2', 'Computer Science', 'Honors Precalculus', 'The West and the World']],
                   ['Philip Kaftan', 'kaftanp21', ['Spanish 4', 'US History', 'Underwater Robotics', 'American Literature', 'free_dot', 'Anatomy & Physiology', 'Precalculus']],
                   ['Phoebe Garfield', 'garfieldp22', ['free_dot', 'Metal Design 1', 'Honors Algebra 2', 'The West and the World', 'European Literature', 'Spanish 3', 'Chemistry']],
                   ['Qingxi Rui', 'ruiq22', ['English Studies: Academic Reading & Writing 2', 'free_dot', 'Honors Algebra 2', 'European Literature', 'Environmental Science', 'Honors Chemistry', 'The West and the World']],
                   ['Qingyang Feng', 'fengq22', ['Honors Chemistry', 'Honors Precalculus', 'The West and the World', 'free_dot', 'English Studies: Academic Reading & Writing 2', 'AP Statistics', 'European Literature']],
                   ['Quade Walls', 'wallsq22', ['Geometry', 'Chemistry', 'free_dot', 'The West and the World', 'European Literature', 'Introduction to Music', 'free_dot']],
                   ['Quinn Kaufer', 'kauferq22', ['Arduinos and Electronics', 'Academic Skills Program', 'free_dot', 'European Literature', 'The West and the World', 'Algebra 2', 'Chemistry']],
                   ['Rafael Borbon', 'borbonr21', ['Music Technology', 'US History', 'French 2', 'free_dot', 'free_dot', 'Honors Algebra 2', 'American Literature']],
                   ['Randolph Liu', 'liul21', ['Honors Chemistry', 'AP US History', 'Presenting Great Decisions', 'Introduction to Graphic Design', 'Calculus', 'AP Statistics', 'American Literature']],
                   ['Reid Johnston', 'johnstonr23', ['French 1', 'Geometry', 'Conceptual Physics', 'World Literature', 'Human Geography', 'free_dot', 'Art Foundations']],
                   ['Richard Norcross', 'norcrossr20', ['Mathematics of Financial Matters', 'Academic Skills Program', 'free_dot', 'Introduction to Graphic Design', 'Literature of Adventure and Exploration', 'Social Entrepreneurship', 'Baseball and American Culture']],
                   ['Riley Jerome', 'jeromer23', ['Spanish 1', 'Geometry', 'Conceptual Physics', 'Spanish 1 LAB', 'Human Geography', 'World Literature', 'free_dot']],
                   ['Runzhe Yao', 'yaor21', ['AP Calculus', 'US History', 'American Literature', 'Spanish 2', 'AP Biology', 'AP Physics: Electricity and Magnetism', 'Research Methods in Science']],
                   ['Ryan Thompson', 'thompsonr22', ['Precalculus', 'free_dot', 'French 2', 'The West and the World', 'European Literature', 'Honors Chemistry', 'Art Foundations']],
                   ['Sadie Harvey', 'harveys21', ['Precalculus', 'Biology', 'AP US History', 'Introduction to Graphic Design', 'free_dot', 'AP Language and Composition', 'Honors Spanish 4: Literature of Spain']],
                   ['Sahla Miller', 'millers20', ['Mathematics of Financial Matters', 'free_dot', 'free_dot', 'Banned Books and Films', 'free_dot', 'Anatomy & Physiology', 'Baseball and American Culture']],
                   ['Sam Owen', 'dickinsons20', ['free_dot', 'Physics', 'free_dot', 'AP Literature and Composition', 'AP Biology', 'AP Statistics', 'Baseball and American Culture']],
                   ['Samantha Ellis', 'elliss23', ['Conceptual Physics', 'Geometry', 'French 2', 'World Literature', 'Human Geography', 'free_dot', 'Band']],
                   ['Samuel Black', 'blacks23', ['Geometry', 'Conceptual Physics', 'World Literature', 'Human Geography', 'Spanish 2', 'free_dot', 'Art Foundations']],
                   ['Samuel Cusano', 'cusanos23', ['Spanish 1', 'Academic Skills Program', 'Algebra 1', 'Spanish 1 LAB', 'Conceptual Physics', 'World Literature', 'Human Geography']],
                   ['Samuel Wadsworth Erickson', 'ericksons20', ['Academic Skills Program', 'AP US History', 'History of Indigenous Peoples of America', 'Banned Books and Films', 'Environmental Science', 'free_dot', 'Precalculus']],
                   ['Shangyi Shen', 'shens20', ['free_dot', 'free_dot', 'Physics', 'AP United States Government and Politics', 'Literature of Adventure and Exploration', 'AP Statistics', 'Research Methods in Science']],
                   ['Shuyang Xu', 'xus20', ['Honors Senior Math', 'free_dot', 'free_dot', 'AP United States Government and Politics', 'AP Chemistry', 'AP Statistics', 'AP Literature and Composition']],
                   ['Silas Summers', 'summerss23', ['free_dot', 'Conceptual Physics', 'Algebra 1', 'Spanish 2', 'Human Geography', 'World Literature', 'free_dot']],
                   ['Siyi Wu', 'wus22', ['English Studies: Academic Reading & Writing 2', 'free_dot', 'Chemistry', 'European Literature', 'The West and the World', 'free_dot', 'Precalculus']],
                   ['Sofia Machado', 'machados22', ['Geometry', 'Chemistry', 'European Literature', 'Spanish 2', 'The West and the World', 'free_dot', 'free_dot']],
                   ['Sofia Stasinos', 'stasinoss23', ['Spanish 1', 'World Literature', 'Algebra 1', 'Spanish 1 LAB', 'Conceptual Physics', 'Introduction to Music', 'Human Geography']],
                   ['Sophie Laurence', 'laurences20', ['AP Calculus', 'Piano and Keyboard Studies', 'free_dot', 'AP United States Government and Politics', 'AP Biology', 'free_dot', 'free_dot']],
                   ['Stefanie Ordway', 'ordways20', ['Mathematics of Financial Matters', 'Metal Design 2', 'free_dot', 'AP United States Government and Politics', 'Environmental Science', 'free_dot', 'AP Literature and Composition']],
                   ['Sylvia Shi', 'shij20', ['Honors Senior Math', 'free_dot', 'Presenting Great Decisions', 'AP United States Government and Politics', 'Environmental Science', 'Spanish 3', 'AP Literature and Composition']],
                   ['Taewoo Kim', 'kimt21', ['AP Calculus', 'US History', 'Mandarin 2', 'American Literature', 'AP Chemistry', 'free_dot', 'free_dot']],
                   ['Tanner Matza', 'matzat20', ['Precalculus', 'Academic Skills Program', 'free_dot', 'AP United States Government and Politics', 'Literature of Adventure and Exploration', 'free_dot', 'French 3']],
                   ['Tarese Morse', 'morset21'],
                   ['Tatum Keighley', 'keighleyt22', ['Geometry', 'Chemistry', 'The West and the World', 'European Literature', 'free_dot', 'Spanish 3', 'free_dot']],
                   ['Taylor Lewis', 'lewist21', ['Spanish 4', 'Biology', 'free_dot', 'Chorus', 'US History', 'Honors Precalculus', 'AP Literature and Composition']],
                   ['Taylor Mull', 'mullt20', ['AP Calculus', 'free_dot', 'free_dot', 'AP Literature and Composition', 'French 5', 'Anatomy & Physiology', 'free_dot']],
                   ['Thomas Hall', 'hallt21', ['free_dot', 'Honors Precalculus', 'AP US History', 'American Literature', 'AP Chemistry', 'Biology', 'Research Methods in Science']],
                   ['Tianai Yuan', 'yuant22', ['English Studies: Academic Reading & Writing 2', 'European Literature', 'French 2', 'free_dot', 'The West and the World', 'Honors Algebra 2', 'Chemistry']],
                   ['Tianze Xu', 'xut20', ['AP Calculus', 'Physics', 'free_dot', 'AP United States Government and Politics', 'AP Chemistry', 'free_dot', 'free_dot']],
                   ['Timothy Pearson', 'pearsont23', ['French 1', 'World Literature', 'Honors Algebra 2', 'French 1 LAB', 'Conceptual Physics', 'free_dot', 'Human Geography']],
                   ['Tom Shan', 'shanw21', ['Honors Senior Math', 'free_dot', 'AP US History', 'free_dot', 'Astronomy', 'AP Physics: Electricity and Magnetism', 'Research Methods in Science']],
                   ['Tracy Cui', 'cuij20', ['free_dot', 'Piano and Keyboard Studies', 'free_dot', 'AP Literature and Composition', 'AP Biology', 'Spanish 3', 'free_dot']],
                   ['Tracy He', 'her22', ['Honors Chemistry', 'Honors Precalculus', 'The West and the World', 'free_dot', 'free_dot', 'AP Statistics', 'European Literature']],
                   ['Tyler Hamel', 'hamelt22', ['free_dot', 'free_dot', 'French 2', 'The West and the World', 'European Literature', 'Algebra 2', 'Chemistry']],
                   ['Utah Bean', 'beanu21', ['Biology', 'Honors Precalculus', 'AP US History', 'free_dot', 'free_dot', 'Spanish 3', 'AP Language and Composition']],
                   ['Wendell Harmer', 'harmerw20', ['Arduinos and Electronics', 'AP Calculus', 'free_dot', 'AP United States Government and Politics', 'Computer Science', 'free_dot', 'AP Language and Composition']],
                   ['Wenjie Xu', 'xuw23', ['Conceptual Physics', 'Drawing 1', 'World Literature', 'Human Geography', 'free_dot', 'Honors Algebra 2', 'free_dot']],
                   ['Will Clark', 'clarkw23', ['Conceptual Physics', 'World Literature', 'Drawing 1', 'Spanish 2', 'Human Geography', 'Honors Precalculus', 'free_dot']],
                   ['Wyatt Thielbar', 'thielbarw21', ['free_dot', 'US History', 'American Literature', 'Chorus', 'Spanish 3', 'Biology', 'Precalculus']],
                   ['Xie Chen', 'xiec21'],
                   ['Xinhao Zhang', 'zhangx22', ['Honors Chemistry', 'Honors Precalculus', 'The West and the World', 'free_dot', 'free_dot', 'AP Statistics', 'European Literature']],
                   ['Yang Cheng', 'chengy22', ['free_dot', 'AP Calculus', 'US History', 'free_dot', 'AP Chemistry', 'AP Physics: Electricity and Magnetism', 'American Literature']],
                   ['Yanqi Chen', 'cheny20', ['free_dot', 'Biology', 'free_dot', 'Banned Books and Films', 'French 4', 'AP Statistics', 'AP Language and Composition']],
                   ['Yanxiu Wu', 'wuy23', ['Conceptual Physics', 'English Studies: Tutorial', 'Drawing 1', 'World Literature', 'free_dot', 'Human Geography', 'Geometry']],
                   ['Yeon-woo Shin', 'shiny23', ['Conceptual Physics', 'Honors Precalculus', 'free_dot', 'World Literature', 'English Studies: Academic Reading & Writing 2', 'Human Geography', 'Band']],
                   ['Ygue Ndinayo', 'ndinayoy20', ['Mathematics of Financial Matters', 'Drawing 1', 'Physics', 'Banned Books and Films', 'free_dot', 'free_dot', 'Precalculus']],
                   ['Yichen Cai', 'caiy23', ['English Studies: Academic Reading & Writing 2', 'World Literature', 'Conceptual Physics', 'Human Geography', 'Algebra 2', 'free_dot', 'free_dot']],
                   ['Yichen Han', 'hany23', ['free_dot', 'World Literature', 'Conceptual Physics', 'free_dot', 'English Studies: Academic Reading & Writing 2', 'Honors Algebra 2', 'Human Geography']],
                   ['Yitong Xu', 'xuy23', ['free_dot', 'English Studies: Academic Reading & Writing 1', 'World Literature', 'Academic Skills Program', 'Conceptual Physics', 'Honors Precalculus', 'Human Geography']],
                   ['Yixuan Peng', 'pengy21', ['Honors Senior Math', 'US History', 'Literature as Social Commentary', 'American Literature', 'free_dot', 'AP Statistics', 'free_dot']],
                   ['Yueying Li', 'liy23', ['English Studies: Academic Reading & Writing 2', 'Conceptual Physics', 'free_dot', 'World Literature', 'Algebra 2', 'Human Geography', 'free_dot']],
                   ['Yusuke Ohga', 'ohgay22', ['free_dot', 'US History', 'Mandarin 2', 'free_dot', 'Calculus', 'Biology', 'American Literature']],
                   ['Yuxuan Hu', 'huy23', ['Conceptual Physics', '3D Design with CAD', 'World Literature', 'free_dot', 'English Studies: Tutorial', 'Honors Algebra 2', 'Human Geography']],
                   ['Yuxuan Li', 'liy22', ['free_dot', 'free_dot', 'American Literature', 'Introduction to Graphic Design', 'US History', 'Biology', 'Precalculus']],
                   ['Zach Hamadeh', 'hamadehz21', ['Artist Blacksmithing: Functional Ironwork', 'Biology', 'Academic Skills Program', 'free_dot', 'US History', 'Honors Precalculus', 'American Literature']],
                   ['Zach Vlcek', 'vlcekz24', ['free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot']],
                   ['Zachary Schmolka', 'schmolkaz22', ['Honors Chemistry', 'Geometry', 'The West and the World', 'Digital Photography 1', 'Spanish 2', 'Algebra 2', 'European Literature']],
                   ['Zack Chen', 'chenz20', ['free_dot', 'AP Calculus', 'Drawing 1', 'Banned Books and Films', 'Literature of Adventure and Exploration', 'AP Statistics', 'free_dot']],
                   ['Zeyu Jin', 'jinz20', ['Mathematics of Financial Matters', 'Metal Design 1', 'Physics', 'American Literature', 'US History', 'free_dot', 'free_dot']],
                   ['Zhe Zhang', 'zhangz22', ['Introduction to Computer Science', 'free_dot', 'The West and the World', 'free_dot', 'European Literature', 'Algebra 2', 'Chemistry']],
                   ['Zhicheng Huang', 'huangz22', ['Geometry', 'free_dot', 'Physics', 'The West and the World', 'free_dot', 'Honors Precalculus', 'European Literature']],
                   ['Zhihuang Cheng', 'chengz22', ['English Studies: Academic Reading & Writing 2', 'Physics', 'The West and the World', 'free_dot', 'Astronomy', 'Honors Precalculus', 'European Literature']]]


teacher_Courses = [['Laurin Parker', 'GY.PARKERL', ['Academic Skills Program', 'Academic Skills Program', 'free_dot', 'Digital Photography 1', 'free_dot', 'free_dot', 'Academic Skills Program']],
                   ['Betsy Riley', 'rileyb', ['Academic Skills Program', 'Academic Skills Program', 'Academic Skills Program', 'Academic Skills Program', 'Academic Skills Program', 'Academic Skills Program', 'free_dot']],
                   ['Jason Chase', 'GY.CHASEJ', ['Introduction to Computer Science', 'free_dot', 'free_dot', 'free_dot', 'Computer Science', 'free_dot', 'free_dot']],
                   ['Matt Murphy', 'murphym', ['free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot', 'free_dot']],
                   ['Denise Manning', 'manningd', ['free_dot', 'free_dot', 'free_dot', 'AP Literature and Composition', 'free_dot', 'free_dot', 'AP Literature and Composition']],
                   ['Dave Bean', 'beand', ['free_dot', 'free_dot', 'US History', 'AP United States Government and Politics', 'free_dot', 'AP Language and Composition', 'AP Language and Composition']],
                   ['Courtney Cook', 'cookc', ['free_dot', 'European Literature', 'European Literature', 'Banned Books and Films', 'free_dot', 'free_dot', 'European Literature']],
                   ['Jay Riley', 'rileyj', ['free_dot', 'free_dot', 'World Literature', 'World Literature', 'Literature of Adventure and Exploration', 'World Literature', 'free_dot']],
                   ['Caroline Murphy', 'murphyc', ['free_dot', 'World Literature', 'Literature as Social Commentary', 'European Literature', 'European Literature', 'free_dot', 'free_dot']],
                   ['Laurel Fiddler', 'fiddlerl', ['free_dot', 'free_dot', 'American Literature', 'American Literature', 'Human Geography', 'Human Geography', 'Human Geography']],
                   ['Peter Moses', 'GY.MOSESP', ['free_dot', 'English Studies: Tutorial', 'English Studies: Academic Reading & Writing 1', 'English Studies: Tutorial', 'English Studies: Tutorial', 'free_dot', 'free_dot']],
                   ['Nancy Barstow', 'barstown', ['English Studies: Academic Reading & Writing 2', 'English Studies: Academic Reading & Writing 1', 'free_dot', 'free_dot', 'English Studies: Academic Reading & Writing 2', 'free_dot', 'Academic Skills Program']],
                   ['Katherine Stack', 'stackk', ['free_dot', 'US History', 'History of Indigenous Peoples of America', 'free_dot', 'US History', 'free_dot', 'free_dot']],
                   ['Brad Clarke', 'GY.clarkeb', ['free_dot', 'free_dot', 'free_dot', 'AP United States Government and Politics', 'free_dot', 'free_dot', 'free_dot']],
                   ['Robert Manning', 'GY.manningr', ['free_dot', 'free_dot', 'The West and the World', 'free_dot', 'The West and the World', 'free_dot', 'free_dot']],
                   ['Alec Newell', 'newella', ['free_dot', 'AP US History', 'AP US History', 'Human Geography', 'free_dot', 'free_dot', 'Baseball and American Culture']],
                   ['Colin Penley', 'GY.penleyc', ['free_dot', 'free_dot', 'Mandarin 1', 'The West and the World', 'Mandarin 1 LAB', 'free_dot', 'The West and the World']],
                   ['Paul Haberstroh', 'GY.haberstrohp', ['Arduinos and Electronics', '3D Design with CAD', 'Underwater Robotics', 'free_dot', 'free_dot', 'Social Entrepreneurship', 'free_dot']],
                   ['Nathaniel Blauss', 'blaussn', ['Honors Senior Math', 'Honors Precalculus', 'free_dot', 'free_dot', 'Algebra 2', 'Honors Precalculus', 'free_dot']],
                   ['Naomi Kramer', 'kramern', ['Geometry', 'Geometry', 'free_dot', 'free_dot', 'free_dot', 'Algebra 2', 'Geometry']],
                   ['Meghan Young', 'GY.youngm', ['Precalculus', 'free_dot', 'free_dot', 'free_dot', 'Environmental Sciences', 'free_dot', 'Precalculus']],
                   ['Ajay Zutshi', 'zutshia', ['AP Calculus', 'AP Calculus', 'Algebra 1', 'free_dot', 'free_dot', 'AP Statistics', 'free_dot']],
                   ['Sara Shiffrin', 'GY.shifrins', ['free_dot', 'free_dot', 'free_dot', 'free_dot', 'Human Geography', 'free_dot', 'Human Geography']],
                   ['Peter Southam', 'GY.southamp', ['Conceptual Physics', 'free_dot', 'Chemistry', 'free_dot', 'AP Chemistry', 'free_dot', 'Research Methods in Science']],
                   ['Aramy Cho', 'choa', ['Honors Chemistry', 'Conceptual Physics', 'free_dot', 'free_dot', 'Conceptual Physics', 'free_dot', 'free_dot']],
                   ['Kristen Drew', 'drewk', ['Biology', 'Biology', 'free_dot', 'free_dot', 'AP Biology', 'Biology', 'free_dot']],
                   ['Nancy Eaton', 'eatonn', ['free_dot', 'Physics', 'Physics', 'free_dot', 'Astronomy', 'AP Physics: Electricity and Magnetism', 'free_dot']],
                   ['Todd Siekman', 'siekmant', ['free_dot', 'Chemistry', 'Conceptual Physics', 'free_dot', 'free_dot', 'Honors Chemistry', 'Chemistry']],
                   ['Adam Leff', 'GY.leffa', ['free_dot', 'free_dot', 'Presenting Great Decisions', 'free_dot', 'French 4', 'free_dot', 'French 3']],
                   ['Douglas Alford', 'alfordd', ['Spanish 4', 'free_dot', 'free_dot', 'Spanish 2', 'Spanish 2', 'free_dot', 'Honors Spanish 4: Literature of Spain']],
                   ['Laurence Leff', 'leffl', ['French 1', 'free_dot', 'French 2', 'French 1 LAB', 'free_dot', 'free_dot', 'free_dot']],
                   ['Tracey Wilkerson', 'wilkerst', ['Spanish 1', 'free_dot', 'free_dot', 'Spanish 1', 'Spanish 3', 'Spanish 3', 'free_dot']]]
